version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "${WEBSERVER_HTTP_PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php
    restart: always
  php:
    build:
      context: .
      dockerfile: Dockerfile-fpm
    volumes:
      - .:/var/www/html

  db:
    image: "mysql:8.0"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
