version: '3.9'

services:
  web:
    build: .
    #image: deforay/vlsm
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - .:/var/www/html
      #- ./docker/php-apache/app.conf:/etc/apache2/sites-enabled/app.conf
      #- ./docker/php-apache/api.conf:/etc/apache2/sites-enabled/api.conf
    environment:
      - DOMAIN=${DOMAIN}
      - API_DOMAIN=${API_DOMAIN}
      - APACHE_PORT=${APACHE_PORT}
    entrypoint: /usr/local/bin/entrypoint.sh
    restart: unless-stopped
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb-strict-mode=OFF --sql-mode=""
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
volumes:
  db_data: {}